name: Run Pytest BDD Tests

on:
  # Trigger the workflow on pushes to the main branch, or pull requests targeting the main branch or manually run the testcases
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Check out the code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.3.2 pluggy==1.5.0 allure-pytest==2.13.5 pytest-bdd==7.2.0 pytest-html==4.1.1 pytest-html-reporter==0.2.9 pytest-metadata==3.1.1

      # Step 4: Run pytest to execute BDD tests
      - name: Run Pytest BDD tests
        run: |
          pytest --capture=tee-sys --disable-warnings --maxfail=5

      # Step 5: Upload test results and logs (optional)
      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: ./reports  # Adjust to your actual reports folder if using one

      # Step 6: (Optional) Publish test coverage to Codecov (if using)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Ensure you set this secret in GitHub
